/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cheshire_test_cdi_nat_JNIHelloWorld */

#ifndef _Included_cheshire_test_cdi_nat_JNIHelloWorld
#define _Included_cheshire_test_cdi_nat_JNIHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cheshire_test_cdi_nat_JNIHelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cheshire_test_cdi_nat_JNIHelloWorld_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
